import { useEffect, useMemo, useRef, useState } from 'react';
type Props = { value: string; error?: string; onChange: (value: string) => void };
const months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const weekdays = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const format = (date: Date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export default function DatePicker({ value, error, onChange }: Props) {
  const today = useMemo(() => { const date = new Date(); date.setHours(0,0,0,0); return date; }, []);
  const [month, setMonth] = useState(new Date(today.getFullYear(), today.getMonth(), 1));
  const [open, setOpen] = useState(false); const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const listener = (event: MouseEvent) => { if (ref.current && !ref.current.contains(event.target as Node)) setOpen(false); }; document.addEventListener('mousedown', listener); return () => document.removeEventListener('mousedown', listener); }, []);
  const days = useMemo(() => { const start = (new Date(month.getFullYear(), month.getMonth(), 1).getDay()+6)%7; const total = new Date(month.getFullYear(), month.getMonth()+1, 0).getDate(); return [...Array.from({length:start},()=>null),...Array.from({length:total},(_,i)=>new Date(month.getFullYear(),month.getMonth(),i+1))]; }, [month]);
  return <div ref={ref} className="relative"><label>Date</label><button type="button" onClick={() => setOpen(!open)} className={`mt-2 flex w-full items-center justify-between rounded-lg border-[1.5px] bg-[#0d0d0d] px-4 py-3.5 text-left ${error ? 'border-[#ff4d4f]' : 'border-[#1a1a1a]'} ${open ? 'border-[#f8d49e]' : ''}`}><span>{value || 'Select Date'}</span><span>▣</span></button>{error && <p className="mt-1.5 text-xs text-[#ff7778]">{error}</p>}{open && <div className="absolute left-0 z-[70] mt-2 w-full min-w-0 max-w-[calc(100vw-2rem)] rounded-xl border-[1.5px] border-[#222] bg-[#0d0d0d] p-4 shadow-2xl sm:min-w-[290px]"><div className="mb-3 flex items-center justify-between font-semibold text-[#f8d49e]"><button type="button" onClick={() => setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><span>{months[month.getMonth()]} {month.getFullYear()}</span><button type="button" onClick={() => setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div><div className="mb-2 grid grid-cols-7 text-center text-[11px] font-semibold text-[#666]">{weekdays.map(day=><span key={day}>{day}</span>)}</div><div className="grid grid-cols-7 gap-1.5">{days.map((day,i)=>!day?<span key={i} className="h-8"/>:<button key={format(day)} type="button" disabled={day<today} onClick={()=>{onChange(format(day));setOpen(false)}} className={`h-8 rounded-md text-[13px] disabled:text-[#333] ${format(day)===format(today)?'border border-[#f8d49e]':''} ${value===format(day)?'bg-gradient-to-br from-[#e0b06b] to-[#c19355] font-bold text-[#1a1206]':''} hover:bg-[#222] hover:text-[#f8d49e]`}>{day.getDate()}</button>)}</div></div>}</div>;
}
